
# Use an official Ruby image to get Jekyll
FROM ruby:3.2

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
RUN apt-get update && \
    apt-get install -y nodejs build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Jekyll and Bundler
RUN gem install jekyll bundler

# Initialize Jekyll site if not present
RUN if [ ! -f "_config.yml" ]; then jekyll new . --force; fi

# # Install the dependencies specified in the Gemfile, or initialize the Gemfile if not present
# RUN if [ -f "Gemfile" ]; then bundle install; else bundle init && bundle install; fi

# # Expose port 4000 to view the website
# EXPOSE 4000

# # Command to serve the site
# CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0"]
